### ISSUE TITLE
This mod is just not working | 1.19.2 fabric

### ISSUE THREAD

**Issue by Surpos0** [Ayutac/creeper-spores-fabric#1]
Game crashed on start, and i got only two mods:
-creeper-spores-fabric
-fabric api 0.67.1
(and btw this version of the game is taged as forge on curseforge)
(and btw it would be nice if you pin issue tab on curseforge)

Time: 2022-11-28 19:06:21
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'creeper-spores'!
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
  at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
  at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
  at net.minecraft.class_310.<init>(class_310.java:459)
  at net.minecraft.client.main.Main.method_44604(Main.java:205)
  at net.minecraft.client.main.Main.main(Main.java:51)
  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:213)
  at crystallauncher.MineClient.main(MineClient.java:36)
Caused by: java.lang.IllegalAccessError: class org.abos.fabricmc.creeperspores.CreeperSpores tried to access private field net.minecraft.class_1299.field_6106 (org.abos.fabricmc.creeperspores.CreeperSpores and net.minecraft.class_1299 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3bf7ca37)
  at org.abos.fabricmc.creeperspores.CreeperSpores.createCreeperlingType(CreeperSpores.java:133)
  at org.abos.fabricmc.creeperspores.CreeperSpores.registerCreeperLike(CreeperSpores.java:102)
  at org.abos.fabricmc.creeperspores.CreeperSpores.lambda$onInitialize$2(CreeperSpores.java:75)
  at org.abos.fabricmc.creeperspores.CreeperSpores.lambda$visitRegistry$1(CreeperSpores.java:66)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at org.abos.fabricmc.creeperspores.CreeperSpores.visitRegistry(CreeperSpores.java:66)
  at org.abos.fabricmc.creeperspores.CreeperSpores.onInitialize(CreeperSpores.java:71)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
  ... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
  at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
  at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
  at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
  Modules: 
    ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    COMCTL32.dll:Biblioteka formant�w czynno�ci u�ytkownika:6.10 (WinBuild.160101.0800):Microsoft Corporation
    CRYPT32.dll:Crypto API32:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
    DNSAPI.dll:Biblioteka DLL interfejsu API klienta us�ugi DNS:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    GDI32.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
    IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2193 (WinBuild.160101.0800):Microsoft Corporation
    IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
    KERNEL32.DLL:Biblioteka DLL klienta Windows NT BASE API:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    KERNELBASE.dll:Biblioteka DLL klienta Windows NT BASE API:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    MSASN1.dll:ASN.1 Runtime APIs:10.0.19041.2251 (WinBuild.160101.0800):Microsoft Corporation
    MpOav.dll:IOfficeAntiVirus Module:4.18.2210.6 (WinBuild.160101.0800):Microsoft Corporation
    NLAapi.dll:Network Location Awareness 2:10.0.19041.2193 (WinBuild.160101.0800):Microsoft Corporation
    NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
    NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
    Ole32.dll:Microsoft OLE for Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
    PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
    RPCRT4.dll:Czas wykonania zdalnego wywo�ywania procedury:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    SHCORE.dll:SHCORE:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    SHELL32.dll:Wsp�lna biblioteka DLL Pow�oki systemu Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    USER32.dll:Wsp�u�ytkowana biblioteka DLL klienta Windows USER API:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    USERENV.dll:Userenv:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    VCRUNTIME140.dll:Microsoft� C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
    VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    WINHTTP.dll:Us�ugi Windows HTTP Services:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    WINMM.dll:MCI API DLL:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    WS2_32.dll:Biblioteka DLL 32-bitowej wersji us�ugi Windows Socket 2.0:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
    WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
    Wldp.dll:Zasady blokady systemu Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
    apphelp.dll:Biblioteka klienta zgodno�ci aplikacji:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    bcrypt.dll:Biblioteka podstawowych element�w kryptograficznych systemu Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
    clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
    combase.dll:Microsoft COM for Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
    dhcpcsvc.DLL:Us�uga klienta DHCP:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    dhcpcsvc6.DLL:Klient DHCPv6:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    fwpuclnt.dll:Interfejs API trybu u�ytkownika funkcji FWP/IPSec:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    gdi32full.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
    gpapi.dll:Interfejs API klienta zasad grupy:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
    jemalloc.dll
    jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    jna11053652775005475730.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
    jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
    kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    lwjgl.dll
    management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    msvcp140.dll:Microsoft� C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
    msvcp_win.dll:Microsoft� C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
    msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    mswsock.dll:Microsoft Windows Sockets 2.0 Dostawca us�ugi:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    napinsp.dll:Dostawca podk�adek nazewnictwa poczty e-mail:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    ncrypt.dll:Router programu NCrypt w systemie Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    ncryptprov.dll:Dostawca magazynu kluczy firmy Microsoft:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    ntdll.dll:Biblioteka NT Layer DLL:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    perfos.dll:Biblioteka DLL obiekt�w wydajno�ci systemu Windows:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    pnrpnsp.dll:Dostawca obszaru nazw PNRP:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
    rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
    sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
    shlwapi.dll:Biblioteka dodatkowych narz�dzi pow�oki:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    ucrtbase.dll:Microsoft� C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
    vcruntime140_1.dll:Microsoft� C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
    verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
    win32u.dll:Win32u:10.0.19041.2251 (WinBuild.160101.0800):Microsoft Corporation
    windows.storage.dll:Interfejs API magazynu systemu Microsoft WinRT:10.0.19041.2248 (WinBuild.160101.0800):Microsoft Corporation
    winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
    zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
  at net.minecraft.client.main.Main.method_44604(Main.java:205)
  at net.minecraft.client.main.Main.main(Main.java:51)
  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:213)
  at crystallauncher.MineClient.main(MineClient.java:36)

-- System Details --
Details:
  Minecraft Version: 1.19.2
  Minecraft Version ID: 1.19.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 17.0.1, Microsoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
  Memory: 6980657792 bytes (6657 MiB) / 9462349824 bytes (9024 MiB) up to 9462349824 bytes (9024 MiB)
  CPUs: 16
  Processor Vendor: AuthenticAMD
  Processor Name: AMD Ryzen 7 3800X 8-Core Processor             
  Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
  Microarchitecture: unknown
  Frequency (GHz): 3.90
  Number of physical packages: 1
  Number of physical CPUs: 8
  Number of logical CPUs: 16
  Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
  Graphics card #0 vendor: NVIDIA (0x10de)
  Graphics card #0 VRAM (MB): 4095.00
  Graphics card #0 deviceId: 0x1c82
  Graphics card #0 versionInfo: DriverVersion=31.0.15.2698
  Memory slot #0 capacity (MB): 8192.00
  Memory slot #0 clockSpeed (GHz): 3.20
  Memory slot #0 type: DDR4
  Memory slot #1 capacity (MB): 8192.00
  Memory slot #1 clockSpeed (GHz): 3.20
  Memory slot #1 type: DDR4
  Virtual memory max (MB): 23206.07
  Virtual memory used (MB): 19932.20
  Swap memory total (MB): 6895.86
  Swap memory used (MB): 536.39
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9000M -Xms9000M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Fabric Mods: 
    creeper-spores: Creeper Spores 2.0.0
    fabric-api: Fabric API 0.67.1+1.19.2
      fabric-api-base: Fabric API Base 0.4.13+0d0f210290
      fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
      fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
      fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
      fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
      fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
      fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
      fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
      fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
      fabric-containers-v0: Fabric Containers (v0) 0.1.37+df3654b390
      fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
      fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
      fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
      fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.1+ad31814d90
      fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
      fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
      fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.30+c6af733c90
      fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
      fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
      fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
      fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
      fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
      fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
      fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
      fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
      fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
      fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
      fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
      fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
      fabric-networking-api-v1: Fabric Networking API (v1) 1.2.7+9244241690
      fabric-networking-v0: Fabric Networking (v0) 0.3.24+df3654b390
      fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
      fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
      fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.28+9244241690
      fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.14+12bfe4ea90
      fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.16+aeb40ebe90
      fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
      fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
      fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
      fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
      fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
      fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
      fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
      fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
      fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.3+1cc24b1b90
      fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
      fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
      fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
      fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
    fabricloader: Fabric Loader 0.14.10
    java: OpenJDK 64-Bit Server VM 17
    minecraft: Minecraft 1.19.2
  Launched Version: fabric-loader-0.14.10-1.19.2
  Backend library: LWJGL version 3.3.1 SNAPSHOT
  Backend API: Unknown
  Window size: <not initialized>
  GL Caps: Using framebuffer using OpenGL 3.2
  GL debug messages: <disabled>
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Maciej\AppData\Roaming\Crystal-Launcher\instances\u.origins2\.minecraft\crash-reports\crash-2022-11-28_19.06.21-client.txt

**Comment by Ayutac** [comment]
yeah sorry, the project page and mod just got approved, so there are a few hickups. Thanks for the feedback, will work on it immediately

**Comment by Ayutac** [comment]
Can reproduce. This error doesn't occur inside the IDE, that's how I didn't notice. But I think I know what's causing it.

**Comment by Ayutac** [comment]
2.0.1 should run, waiting for CF to approve the upload before I delete the broken 2.0.0
